name: Terraform Module Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: stackgobrr/common-github-actions/.github/workflows/terraform-module-release.yml@main
    with:
      terraform_version: "1.14.1"
      module_type: "cognito"
      enable_breaking_change_detection: true
    permissions:
      contents: write
